### ISSUE TITLE
Header includes

### ISSUE THREAD

**Issue by lczech** [RosettaCommons/binder#10]
The documentation does not mention that my project's `#include` directives have to use `<...>` instead of `"..."`. This could me mentioned somewhere ;-)

**Comment by lczech** [comment]
To clarify, http://cppbinder.readthedocs.io/en/latest/basics.html#preparing-the-input-file mentions this for the all-including header, but not that this is also necessary for all other includes in my project's headers.

**Comment by lyskov** [comment]
I see... yes, the include `<..>` notation is needed in all headers because otherwise Binder will not be able to determent where is particular class/function/enum came from. Adding @xlong2, Xiyao could you please looks this up?

**Comment by Worsman** [comment]
Would the recommendation be to **recursively** include all #include <header.h> in the all-including header.hpp file?? For larger projects, this could lead to very large list of files despite only wanting to expose a subset of classes.

example:

CClassA.h >> have 2 includes  
CClassB.h & CClassC.h
but each of B & C also have 2 x includes 

this means all-including header.hpp >> 
#include <CClassA.h>
#include <CClassB.h>
#include <CClassC.h>

#include <CClassD.h>
#include <IncludePathY\CClassE.h>

#include <IncludePathX\CClassF.h>
#include <CClassG.h>

what makes it more complicated it this includes relying on project level include paths to resolve

OR am I misunderstanding the aim of the listing in the all-including header.hpp??
