### ISSUE TITLE
Rationale for pybind11 fork

### ISSUE THREAD

**Issue by mc-allen** [RosettaCommons/binder#102]
Was wondering about the fork of pybind11. It would be great to have in the docs some description of what was changed and why, and if/how you'll stay in sync with updates to pybind11. This is mainly a concern as a someone who might take a long-term dependency on a tool like this, and a preference to not have to be tied to an older version of pybind11. Thanks.

**Comment by lyskov** [comment]
Binder needs to be in lock-step with Pybind11 version in order for resulted binding to be compilable and function properly. This is mostly due to need to use custom call-back code. Also, in some cases we have to apply custom patches (none at the moment though) to Pybind11 upstream.
