### ISSUE TITLE
Support for pure virtual class (via pybind11 Trampoline class)  ?

### ISSUE THREAD

**Issue by kzjeef** [RosettaCommons/binder#111]
Hi, 

I want to know does there is any plan to support pure virtual function, 
By the document of pybind11 (https://pybind11.readthedocs.io/en/stable/advanced/classes.html#overriding-virtual-functions-in-python) 

Because pure virtual class in c++ is not constructible, so the direct binding is impossible, it require a wrap class and call `PYBIND11_OVERLOAD_PURE` macro.

From my knowledge of binder,  it currently don't support this function, does any plan to support this function?

**Comment by lyskov** [comment]
This is already supported. Please see 
https://github.com/RosettaCommons/binder/blob/master/test/T09.overload.hpp#L30 and https://github.com/RosettaCommons/binder/blob/master/test/T11.override.ref#L37 for reference output.

**Comment by lyskov** [comment]
@kzjeef if you have case when this does not work properly, could you please post minimal example here so i can look at it locally? Thanks,

**Comment by kzjeef** [comment]
I think I found the problem, my header is named as "xxxx.h", so it's only generate directly mapping from function to function, but If I change the header file name to xxx.hpp, it's seems can generate correct result, 

How the binder choose c or c++ ? only by the file's name ?

**Comment by kzjeef** [comment]
@lyskov This is my test case, command line is: `binder --root-module example --bind="example" --single-file  -annotate-includes example.cc -- -std=c++11`

It have two issue: 

1. It report one error: 
`Warning: file_name_prefix_for_binder could not determent file name for decl: example::Msg, result is too short!`

But the define of Msg is in the header.

[example.zip](https://github.com/RosettaCommons/binder/files/5006786/example.zip)

2. The example::Module is a pure virtual class, it should use a Trampoline class, but it doesn't.
```
		pybind11::class_<example::Module, std::shared_ptr<example::Module>> cl(M("example"), "Module", "");
```

**Comment by lyskov** [comment]
Thank you for example @kzjeef ! There is a few issues at play here:
- on your platform Binder was not able to bind neither `MessageLists` nor `MessageList` classes. These classes use std container which usually require special handling
- your `Module` class have pure-virtual function `virtual void Forward(Context* run_ctx, MessageLists* inputs) = 0;`. In order to be able to create trampoline class Binder have to be able to bind all pure-virtual functions which in turn require Binder to be able to bind all argument types.

Easiest way to solve this would probably be to use `+binder` directives to bind both `std::vector` and `std::deque` classes. Please see https://cppbinder.readthedocs.io/en/latest/config.html for description of this feature and https://github.com/RosettaCommons/binder/blob/master/test/T40.stl.config https://github.com/RosettaCommons/binder/blob/master/test/T40.stl.hpp https://github.com/RosettaCommons/binder/blob/master/test/T40.stl.ref for example usage of this feature.

We also provide stock binders for vector and map classes here which you can use to design binder for `std::deque` type: https://github.com/RosettaCommons/binder/blob/master/source/stl_binders.hpp

Hope this helps,

**Comment by kzjeef** [comment]
@lyskov Thanks for your detailed reply, I'll try your method.

**Comment by kzjeef** [comment]
@lyskov I have finish this bind by modify the type, 

I found pybind11 can bind std::deque<std::shared_ptr<Message>>
also std::vector<std::deque<std::shared_ptr<Message>>>

but it cannot bind std::vector<**std::shared_ptr**<std::deque<std::shared_ptr<Message>>>>, the compiler will report:
```
pybind11/2.5.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/cast.h: In instantiation of ‘struct pybind11::detail::copyable_holder_caster<std::vector<std::shared_ptr<sniper::Message> >,
std::shared_ptr<std::vector<std::shared_ptr<sniper::Message> > > >’:
pybind11/2.5.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/cast.h:1557:7:   required from ‘class pybind11::detail::type_caster<std::shared_ptr<std::vector<std::shared_ptr<sniper::Messa
ge> > >, void>’
pybind11/2.5.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/stl.h:183:5:   required from ‘constexpr const auto pybind11::detail::list_caster<std::vector<std::shared_ptr<std::vector<std:
:shared_ptr<sniper::Message> > > >, std::shared_ptr<std::vector<std::shared_ptr<sniper::Message> > > >::name’
pybind11/2.5.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/stl.h:183:5:   required from ‘struct pybind11::detail::list_caster<std::vector<std::shared_ptr<std::vector<std::shared_ptr<sn
iper::Message> > > >, std::shared_ptr<std::vector<std::shared_ptr<sniper::Message> > > >’
pybind11/2.5.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/stl.h:186:49:   required from ‘class pybind11::detail::type_caster<std::vector<std::shared_ptr<std::vector<std::shared_ptr<sn
iper::Message> > > >, void>’
pybind11/2.5.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/cast.h:1804:55:   required from ‘pybind11::tuple pybind11::make_tuple(Args&& ...) [with pybind11::return_value_policy policy
= (pybind11::return_value_policy)1u; Args = sniper::Context*&, std::vector<std::shared_ptr<std::vector<std::shared_ptr<sniper::Message>, std::allocator<std::shared_ptr<sniper::Message> > > >, std::allocator<std::shared_ptr<std::vector<s
td::shared_ptr<sniper::Message>, std::allocator<std::shared_ptr<sniper::Message> > > > > >&]’
pybind11/2.5.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/cast.h:1995:74:   required from ‘pybind11::detail::simple_collector<policy>::simple_collector(Ts&& ...) [with Ts = {sniper::C
ontext*&, std::vector<std::shared_ptr<std::vector<std::shared_ptr<sniper::Message>, std::allocator<std::shared_ptr<sniper::Message> > > >, std::allocator<std::shared_ptr<std::vector<std::shared_ptr<sniper::Message>, std::allocator<std::
shared_ptr<sniper::Message> > > > > >&}; pybind11::return_value_policy policy = (pybind11::return_value_policy)1u]’
pybind11/2.5.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/cast.h:2139:64:   required from ‘pybind11::detail::simple_collector<policy> pybind11::detail::collect_arguments(Args&& ...) [
with pybind11::return_value_policy policy = (pybind11::return_value_policy)1u; Args = {sniper::Context*&, std::vector<std::shared_ptr<std::vector<std::shared_ptr<sniper::Message>, std::allocator<std::shared_ptr<sniper::Message> > > >, s
td::allocator<std::shared_ptr<std::vector<std::shared_ptr<sniper::Message>, std::allocator<std::shared_ptr<sniper::Message> > > > > >&}; <template-parameter-1-3> = void]’
pybind11/2.5.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/cast.h:2159:73:   required from ‘pybind11::object pybind11::detail::object_api<Derived>::operator()(Args&& ...) const [with p
ybind11::return_value_policy policy = (pybind11::return_value_policy)1u; Args = {sniper::Context*&, std::vector<std::shared_ptr<std::vector<std::shared_ptr<sniper::Message>, std::allocator<std::shared_ptr<sniper::Message> > > >, std::al
locator<std::shared_ptr<std::vector<std::shared_ptr<sniper::Message>, std::allocator<std::shared_ptr<sniper::Message> > > > > >&}; Derived = pybind11::handle]’
/home/jiejing/sniper_video/python/runtime_binding.hpp:32:5:   required from here

pybind11/2.5.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/cast.h:1483:5: error: static assertion failed: Holder classes are only supported for custom types
```

**Comment by lyskov** [comment]
@kzjeef this is odd, i would expect that if you can bind `std::deque<std::shared_ptr<A>>` then binding `std::vector<std::deque<std::shared_ptr<A>>>` should work as well. Could you please double check that you header file have `PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);` defined at the top? Also, have you tried to replicate this as minimal example (ie without Binder involved) as Pybind11 code? If so, then could you please post it here so we can double check if something obvious is missing. And if not then it would probably should be submitted to Pybind11 project as issue. Thanks,
