### ISSUE TITLE
Tests fail on Ubuntu 18.04?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RosettaCommons/binder#117]
When I ran `./build-and-run-tests.py` on Ubuntu 18.04 (using master @ 022cd0d), I get the following errors:
https://gist.github.com/EricCousineau-TRI/4bd4615baeabc2c3b071473f597cbae5

FTR, the regression test errors seem pretty small, like something about an `enum class`?

**Comment by EricCousineau-TRI** [comment]
Oh, I lied about the diff's being small. Just ran `--accept` and didn't realize that the tests failed fast without it.

**Comment by lyskov** [comment]
fix is now in master, so i am closing this issue
