### ISSUE TITLE
Should mention the importance of trailing `/` for `--prefix`?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RosettaCommons/binder#118]
At first, I thought `--prefix` was gonna be something like an output directory. I would run it on some test code with something like `--prefix /tmp/binder`, would see the folder `/tmp/binder` created, but wouldn't see any of those files.

I then hashed around for a bit to try out different LLVM versions, including the source-built version (hence my coming across #117), only to realize that I just needed to specify `/tmp/binder/` :P

**Comment by HFTrader** [comment]
This seems to be on purpose? I was looking at the code for issue #57 and it seems that the code does not add a trailing slash on purpose.

**Comment by lyskov** [comment]
This was indeed done on purpose, to make possible to specify both file-like-prefix and dir-like-prefix's
