### ISSUE TITLE
Minor: Command line options doc

### ISSUE THREAD

**Issue by lczech** [RosettaCommons/binder#12]
In the [documentation for the command line options ](http://cppbinder.readthedocs.io/en/latest/config.html#command-line-options), the dash symbol `–` is a single wide dash for all options, instead of the needed two normal dashes `--`. Thus, copy-paste from the documentation does not work.

**Comment by andriish** [comment]
Hi @lyskov ,
it looks it has been solved.

Best regards,

Andrii

**Comment by lyskov** [comment]
Thanks for heads-up @andriish ! Closing.
