### ISSUE TITLE
Tests don't seem like they're run on CI?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RosettaCommons/binder#120]
Split off from #117

When I look at CI, it doesn't look like the tests are run? (they assume CTest, but there are no CTest targets configured?)
For example:
https://github.com/RosettaCommons/binder/runs/896230166#step:3:1076
```
+ ctest . --output-on-failure
Test project /github/workspace
No tests were found!!!
```

**Comment by andriish** [comment]
Hi @eacousineau ,

The ctest variation is under development.
 Therefore, the ctest command  is present in CI but the CI does not report a failure if the ctest command fails or no ctests found.
There will be a merge request with an implementation of ctest soon.

Best regards,

Andrii

**Comment by andriish** [comment]
This can be closed, I think.

**Comment by EricCousineau-TRI** [comment]
SGTM!
