### ISSUE TITLE
Constructors with stl classes in config

### ISSUE THREAD

**Issue by andriish** [RosettaCommons/binder#142]
Hi @lyskov ,

I have this code
```
#ifndef FAKE_H
#define FAKE_H
#include <string>
#include <fstream>
namespace FAKE {
class fakeclass   {
public:
    fakeclass(const std::string& filename){};
    fakeclass(int& f){};
    fakeclass(std::istream &){};
    ~fakeclass(){};
    bool skip(const int a){return true;};
};
}
#endif

```
and two configs

1
```
+include <fake.h>
+namespace FAKE

```

and

2

```
+include <fake.h>
+namespace FAKE
-function FAKE::fakeclass::fakeclass(int &)
-function FAKE::fakeclass::fakeclass(std::istream &)
-function FAKE::fakeclass::fakeclass(std::basic_istream<char> &)
-function FAKE::fakeclass::skip

```
The result from  2 is the same as from 1 ) minus the skip function and the constructor with int.

The constructors with stream are not affected.

CentOS7/llvm6/Clang6

Best regards,
Andrii

**Comment by lyskov** [comment]
I just double checked: the `-function` config directive should be supplied with _the exact_ constructor type as Binder tries to generate. On my test system the `istream` constructor was bound with `fakeclass::fakeclass(class std::basic_istream<char> &)` signature. Using this exact signature indeed disable this constructor bindings.

I also just pushed patch that added standard name for `istream` type so now using just `std::istream &` should work too.

I am closing this for now but please let me know if still having trouble with this issue. Thanks,
