### ISSUE TITLE
LLVM 6.0 needed?

### ISSUE THREAD

**Issue by jtrmal** [RosettaCommons/binder#148]
Hi, I'm thinking about testing this for one of the research projects I participate on and went over the install instructions -- I was just wondering if the release_60 for clang/llvm is a requiremement? Or can I use later/more modern LLVM releases?
Thanks for the work on the project -- looks great!

**Comment by andriish** [comment]
Hi @jtrmal ,

The CI tests binder using versions of LLVM up to 11 (as comes witj Fedora),  I think.

Best regards,

Andrii

**Comment by jtrmal** [comment]
thanks a lot!
y.
