### ISSUE TITLE
Typo in documentation of return value policy config parameter

### ISSUE THREAD

**Issue by MartinKielhornPhilips** [RosettaCommons/binder#149]
The example 

`+default_pointer_return_value_policy           pybind11::return_value_policy::reference
`

at the bottom of this page
https://cppbinder.readthedocs.io/en/latest/config.html#config-file-directives

is not handled in code. Possibly this line should be 
`+default_member_pointer_return_value_policy           pybind11::return_value_policy::reference
`

**Comment by lyskov** [comment]
Thank you for letting me know @MartinKielhornPhilips ! This should be fixed in 3e65a2f0469268e7a87504c4f83866ab62a63edc
