### ISSUE TITLE
Analyze code failed on msvc project

### ISSUE THREAD

**Issue by RedSkotina** [RosettaCommons/binder#15]
os: windows 7 x64
compilers: msvs 2015 sp3, clang 4.0.0 x86 (downloaded as binaries from official clang site)
I just compile binder via clang 4.0.0 x86 (using patched sources  and include 'ciso646' https://github.com/RosettaCommons/binder/pull/3) and take binder.exe.
now when i try use it on my msvc project then take errors 

> 
> e:\code\zog\pyunitylib.git\extras>binder --root-module pyunitylib --prefix ../src --config ./pyunitylib.binder.conf   py_unity_unpacker_lib.h   -- -std=c++11 -Ie:\code\zog\unity-unpacker-lib.git\include   -Ie:\code\zog\unity-unpacker-lib.git\unity_unpacker_lib   -Ie:\code\zog\unity-unpacker-lib.git -DNDEBUG  
> error: invalid argument '-std=c++11' not allowed with 'C/ObjC'
> In file included from e:\code\zog\pyunitylib.git\extras\py_unity_unpacker_lib.h:1:
> In file included from e:\code\zog\unity-unpacker-lib.git\unity_unpacker_lib\unity_unpacker_lib.h:4:
> In file included from e:\code\zog\unity-unpacker-lib.git\plugins/plugin.h:3:
> In file included from e:\code\zog\unity-unpacker-lib.git\include\Pluma/Pluma.hpp:32:
> In file included from e:\code\zog\unity-unpacker-lib.git\include\Pluma/Provider.hpp:32:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\string:6:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\istream:6:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ostream:6:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ios:6:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xlocnum:7:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\cmath:647:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xtgmath.h:8:
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xtr1common:213:22: error: use of undeclared identifier 'char16_t'
>         struct _Is_integral<char16_t>
>                             ^
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xtr1common:219:22: error: use of undeclared identifier 'char32_t'
>         struct _Is_integral<char32_t>
>                             ^
> In file included from e:\code\zog\pyunitylib.git\extras\py_unity_unpacker_lib.h:1:
> In file included from e:\code\zog\unity-unpacker-lib.git\unity_unpacker_lib\unity_unpacker_lib.h:4:
> In file included from e:\code\zog\unity-unpacker-lib.git\plugins/plugin.h:3:
> In file included from e:\code\zog\unity-unpacker-lib.git\include\Pluma/Pluma.hpp:32:
> In file included from e:\code\zog\unity-unpacker-lib.git\include\Pluma/Provider.hpp:32:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\string:6:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\istream:6:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ostream:6:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\ios:6:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xlocnum:10:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\streambuf:6:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xiosbase:6:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xlocale:8:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdexcept:6:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\exception:7:
> In file included from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\type_traits:6:
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xstddef:404:14: error: use of undeclared identifier 'char16_t'
>         struct hash<char16_t>
>                     ^
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xstddef:410:14: error: use of undeclared identifier 'char32_t'

and etc
I not familar with llvm and clang but seems binder use clang analyzer but not pass option "-fms-compatibility-version=19".
how i can pass this option via command option or from source?

**Comment by RedSkotina** [comment]
ok. seeems using '-fms-compatibility-version=19' after '--' solve my problem.

**Comment by lyskov** [comment]
Great, thank you for sharing workaround!
