### ISSUE TITLE
Forward declared inner functions

### ISSUE THREAD

**Issue by ThFe** [RosettaCommons/binder#156]
Hi,
I ran into a problem when binding classes with forward declared inner classes.
In particular, when binding the code
```
struct outer {
	struct inner { int a; };  // ok
	struct inner2;             // ok
	struct inner3;             // not ok

	void f( inner *i, inner2 *i2, inner3 *i3 ){};

	struct inner2 { int b; };
};

struct outer::inner3 { int c; };
```
the inner class `inner3` will not be included.
However, I would have expected bindings for `inner3` as well.
Do you agree?

**Comment by lyskov** [comment]
Yes, - PR for adding support for this is welcome! I will add comment on PR page and close this for now.
