### ISSUE TITLE
Binder includes in singlefile 

### ISSUE THREAD

**Issue by RedSkotina** [RosettaCommons/binder#16]
If i use option '-single-file' then 

```
#include <map>
#include <memory>
#include <stdexcept>
#include <functional>

#include <pybind11/pybind11.h>

```

placed before PYBIND11_PLUGIN function , but after other modules code and cant be used.
Please move this includes to top of singlefile when generate single file.

**Comment by lyskov** [comment]
Could you please elaborate why this create a problem? The single-file option is just concatenating all output file into one and place `main` (the one that contain `PYBIND11_PLUGIN`) at the end. In result each portion should have its own include section as seen here: https://github.com/RosettaCommons/binder/blob/master/test/T00.basic.ref so appropriate include is guaranteed to be included first, before actual code that used them etc.

**Comment by RedSkotina** [comment]
I have all include file https://bitbucket.org/RedSkotina/pyuul/src/b3aaa685d1261b5c28b9e04a9c6dcc04e5738f73/extras/py_unity_unpacker_lib.h?at=devel&fileviewer=file-view-default
and generated file https://bitbucket.org/RedSkotina/pyuul/src/b3aaa685d1261b5c28b9e04a9c6dcc04e5738f73/src/pyuul/pyuul.cpp?at=devel&fileviewer=file-view-default#pyuul.cpp-2067
I have expressions in allinclude file for instancing templates.

**Comment by lyskov** [comment]
Ah, i see! So what you need to do is following: create one more include file (say `all_includes.h`) and inside it put `#include <py_unity_unpacker_lib.h>` line.

You see, in order for Binder to correctly deduce appropriate `include` for each line of code the all-include file should only contain includes (no code).

Please let me know if that fixed it!

**Comment by RedSkotina** [comment]
no changes.
functional placed after `void bind_std_xutility(std::function< pybind11::module &(std::string const &namespace_) > &M)` and etc

i use workaround via `+include` directive

**Comment by lyskov** [comment]
Oh, i forgot to mention: you need to use absolute include paths, so for example `#include <../include/tcl/Tree.h>` will need to be replaced with something like `#include <tcl/Tree.h>` or what ever is appropriate for your system.
