### ISSUE TITLE
confused about using template class type as parameter in declaration

### ISSUE THREAD

**Issue by KeyID7** [RosettaCommons/binder#163]
Suppose my header file contains such function declaration:

`void foo(std::vector<int>);`

Since it's only a declaration, the template class std::vector will not be instantiated thus binder will skip the function. However, I expect binder to generate the binding for this function. The .o files containing the definitions will be linked at last.

I have seen issues about templates, like #80 and #101, and know I can use explicit instantiation. But it will be hard to add explicit instantiation for a large project. Is there any simpler way?

**Comment by lyskov** [comment]
@KeyID7 issue here is that during the Binding process Binder is getting type that is not fully instantiated so it can not be bound. It seems plausible that there should be a way to instantiate templates within LLVM framework but so far this has not worked for me. But if someone knows how to do it and can share such info that i will be happy to implement this!
