### ISSUE TITLE
Wrong documentation about return_policy

### ISSUE THREAD

**Issue by RedSkotina** [RosettaCommons/binder#18]
Found old(wrong) notes about `default_pointer_return_value_policy` and etc
http://cppbinder.readthedocs.io/en/latest/config.html
From source code here no such option, but exist `default_member_pointer_return_value_policy`
 and etc.
Please fix documentation

**Comment by lyskov** [comment]
Thank you for letting me know! Fixed in dababfe3e12569ac4371502286811e6fb1926ef3
