### ISSUE TITLE
Error: expected unqualified-id before numeric constant

### ISSUE THREAD

**Issue by FRidh** [RosettaCommons/binder#19]
I just ran in the following issue https://github.com/fmtlib/fmt/issues/398.
With fmt master at https://github.com/fmtlib/fmt/commit/d49f2061838ec4c0ee9951d917d06448c0aa65a2 or version 3.0.1 I was able to successfully build binder.

**Comment by lyskov** [comment]
Thank you for letting me know @FRidh! I will update the `fmt` version.
