### ISSUE TITLE
Build with Visual Studio 2015

### ISSUE THREAD

**Issue by trelau** [RosettaCommons/binder#2]
I generated the project files using cmake and then build the "INSTALL" solution. A lot of executables get built but binder.exe is nowhere to be found. I used the clang platform tools for the binder project to avoid compile errors. Where/when is the binder executable suppose to be built?

**Comment by lyskov** [comment]
On Unix the binaries will be placed inside `build_prefix/bin` dir. I am not familiar with MSVC project is setup for the LLVM but i am guessing that the crucial part that now might be missing is adding Binder sources as a sub-project for clang project. The analogous step in Unix is described here http://cppbinder.readthedocs.io/en/latest/install.html#building see the line commented as 'Create symlink pointing to binder/src dir'. My guess that you will need to create MSVC for Binder (it contain just a few files so it should be easy) and insert this this projects into LLVM/Clang project.

If you figure out how to make this work then patch to our docs emplaning the building procedure would be most welcome!

Thanks,

**Comment by lyskov** [comment]
@trelau i have not heard back form you regarding this so i will consider this issue resolved for now.
