### ISSUE TITLE
Please update docs: installation documentation has incorrect info

### ISSUE THREAD

**Issue by shakfu** [RosettaCommons/binder#211]
The installation documentation on https://cppbinder.readthedocs is dated and does not work. The only correct advice should be to run the `build.py` scripts which do work.

**Comment by lyskov** [comment]
@shakfu could you please elaborate? Particularly, which documentation step(s) failed? Thanks,

**Comment by shakfu** [comment]
@lyskov, sorry, my bad, I should have been more specific: in the [install/building](https://cppbinder.readthedocs.io/en/latest/install.html) section of the binder docs, the following steps are provided.


```bash
# clone Binder
cd $HOME
git clone https://github.com/RosettaCommons/binder.git

# Create build dir
mkdir $HOME/prefix && cd $HOME/prefix

# Clone  LLVM
git clone http://llvm.org/git/llvm.git llvm && cd llvm
git checkout release_60
...
```
Once cannot proceed as specified because **http://llvm.org/git/llvm.git** repo is not longer provided as a service. llvm can be downloaded, I believe, from GitHub presently but the structure of the repo is probably different from the above.

I suggest that this part of the manual is skipped and that users are just told to run the `build.py` script which works perfectly for macOS and linux (I've tested both).

**Comment by shakfu** [comment]
@lyskov 

I just converted all my headers to pointy brackets as suggested and all unknowns [disappeared](https://github.com/shakfu/pyhola/tree/main/bind) 😄 

I made a [python script](https://github.com/shakfu/pyhola/blob/main/scripts/convert_braces.py) to do this recursively (with backup of course). I'll attach it here in case anyone is interested. As you advised, it cannot be understated how important doing this is for binder to work properly!

[convert_braces.py.zip](https://github.com/RosettaCommons/binder/files/9050714/convert_braces.py.zip)

**Comment by shakfu** [comment]
@lyskov Fyi I have updated the script above to provide the following binder-friendly features:

**Header Transformations**
- Transform include quotes to pointy brackets
- Transform relative to absolute include path references
- Transform `#pragma once` to header guards

**Analysis**
- Generate graphviz (pdf|png|svg) graph of header dependencies.

The script is now called `header_utils.py` and has it's own [github project](https://github.com/shakfu/header_utils).

**Comment by lyskov** [comment]
> One cannot proceed as specified because the http://llvm.org/git/llvm.git repo is not longer provided as a service. llvm can be downloaded, I believe, from GitHub presently but the structure of the repo is probably different from the above.

-- thank you for letting me know, - i will update URL's in doc shortly.

> I suggest that this part of the manual is skipped and that users are just told to run the build.py script which works perfectly for macOS and linux (I've tested both).

-- reason for keeping this part of the docs is because there is many "right" ways to install Binder. Particularly in some cases it might be advisable to compile it against system installed LLVM sources. So it is important that general ideas of install is outlined.

**Comment by lyskov** [comment]
re `header_utils.py`: - this look very useful, thank you for writing and sharing this!!! I was thinking of writing something similar soon to transform headers in one of my projects, so good timing! A few thoughts/ideas on script functionality to expand it usability:
- would it be possible to supply target-dir (instead of transformation in place)?
- would it be possible to make transformation of include guards optional?
- would it be possible to take list of possible header file extensions? (one of my project for example using `.hh`) (or maybe just hardcode `.hh` ?)


Thanks,

**Comment by lyskov** [comment]
FYI: i updated Binder docs and added docs to https://github.com/shakfu/header_utils - hope this is ok with you!

**Comment by lyskov** [comment]
Also: LLVM Git path should be fixed now, again: - thank you for letting me know about this issue.

**Comment by shakfu** [comment]
@lyskov Thanks for the update docs and also the tips for improving `header_utils`

>would it be possible to supply target-dir (instead of transformation in place)?
would it be possible to make transformation of include guards optional?
would it be possible to take list of possible header file extensions? (one of my project for example using .hh) (or maybe just hardcode .hh ?)

All of the above tweaks are good and reasonable. I'll implement them shortly.

**Comment by shakfu** [comment]
Hi @lyskov 

I've had my first crack at implementing your suggestions. I think they are reasonably covered. Please do provide any further feedback if any.

**Comment by lyskov** [comment]
Awesome, - thank you @shakfu !
