### ISSUE TITLE
Variadic templates

### ISSUE THREAD

**Issue by kkrissian-gpfw** [RosettaCommons/binder#213]
Hello,

Thank you for the great work with Binder and pybind11, I have been using it for the last months to convert a previous binding system with success. I will report several issues and suggestions from this experience. The first one is an issue while binding variadic templates. The following code shows a simple example of a code creating the issue:

```
#pragma once

#include <array>
[variadic_templates.tar.gz](https://github.com/RosettaCommons/binder/files/9302113/variadic_templates.tar.gz)

namespace variadic_template {

	template<class T,int N,int... Ns> struct Array : std::array<Array<T,Ns...>,N> {};
	// Terminal case
	template<class T,int N> struct Array<T,N> : std::array<T,N> {};

	// Needed to instanciate the class instance and bind it
	struct st2: public Array<int, 2,2> {};
}

```
The generated code creates a wrong name for the class: _**variadic_template::Array<int,2,<2>>**_
instead of  **_variadic_template::Array<int,2,2>_**, which results in compilation errors

I could fix this issue with the following patch
```
diff --git a/source/class.cpp b/source/class.cpp
index a6e39dc..54e9f85 100644
--- a/source/class.cpp
+++ b/source/class.cpp
@@ -51,7 +51,12 @@ string template_specialization(clang::CXXRecordDecl const *C)
                        // if( t->getTemplateArgs()[i].isInstantiationDependent() ) break;  // avoid explicitly specifying SFINAE related arguments
 
                        // outs() << " template argument: " << template_argument_to_string(t->getTemplateArgs()[i]) << "\n";
-                       templ += template_argument_to_string(t->getTemplateArgs()[i]) + ",";
+                       // templ += template_argument_to_string(t->getTemplateArgs()[i]) + ",";
+                       std::string template_arg = template_argument_to_string(t->getTemplateArgs()[i]);
+                       if ((template_arg[0] == '<') and (template_arg[template_arg.size()-1]=='>'))
+                               template_arg = template_arg.substr(1, template_arg.size()-2);
+                       if (template_arg.size()>0)
+                               templ += template_arg + ",";
 
                        // if( t->getTemplateArgs()[i].ArgKind() == TemplateArgument::ArgKind::Integral ) outs() << " template arg:" << t->getTemplateArgs()[i].<< "\n";
                        // outs() << expresion_to_string( t->getTemplateArgs()[i].getAsExpr() ) << "\n";

```
I attach a tarball file containing a self compiling code and a patch for binder.
Let me know if you consider that this fix can be included in the next release.

Regards,

Karl Krissian
[variadic_templates.tar.gz](https://github.com/RosettaCommons/binder/files/9302131/variadic_templates.tar.gz)

**Comment by lyskov** [comment]
Thank you for letting me know about this @kkrissian-gpfw , - this super useful! Also thank you for the patch and the test case, - this will make testing much easier for me! - in short yes, - i will be happy to merge this but i will need to run extensive tests to make sure that this does not break any existent template bindings, - i will let you know how it goes.

**Comment by lyskov** [comment]
My tests looks good so this is now merged in master, - thank you @kkrissian-gpfw !

**Comment by kkrissian-gpfw** [comment]
Great, thank you
