### ISSUE TITLE
Don't include standard libraries?

### ISSUE THREAD

**Issue by trelau** [RosettaCommons/binder#22]
It looks like a TON of standard libraries are getting written to every binding file, and multiple times. Is there an option to include only the headers needed in the file?

![image](https://cloud.githubusercontent.com/assets/8950602/26389711/4a10c916-4029-11e7-9bb2-db5a052f06c9.png)

I'm using VS 2015.

**Comment by lyskov** [comment]
This is probably due to `--annotate-includes` option used in Binder call. It is useful to check what object pulled certain include files. Avoiding specifying this option should solve this.
