### ISSUE TITLE
`__div__` does not exist in python 3.x, only 2.x. Python3 uses either `__truediv__` or `__floordiv__`

### ISSUE THREAD

**Issue by zwimer** [RosettaCommons/binder#232]
Binder currently maps `operator/` to `__div__`; but that magic function doesn't exist in python3, which I assume is what binder generates for given that python2 was end of life years ago.

You can see the bug here:
https://github.com/RosettaCommons/binder/blob/7c28c46af1008119237b327d9b1fbfcb23d844a8/source/function.cpp#L47

This is also true for `__idiv__`.

**Comment by lyskov** [comment]
Thank you for letting me know @zwimer ! This is now fixed in 5f0a7bd

**Comment by zwimer** [comment]
@lyskov This doesn't fix `__itruediv__` for `/=`
