### ISSUE TITLE
Spack support

### ISSUE THREAD

**Issue by kliegeois** [RosettaCommons/binder#243]
Spack https://github.com/spack/spack is a tool developed to ease the installation of libraries by keeping track of their dependencies and by providing a way to install them. 
There is currently no spack package for binder (but there is one for llvm and one for pybind11 https://spack.readthedocs.io/en/latest/package_list.html# ).

Would a spack package for binder be something of interest for other binder users/use cases?
@lyskov have you heard of spack, do you have thoughts about a spack recipe for binder?

**Comment by lyskov** [comment]
Sorry for the late reply @kliegeois ! - i personally have not use this tool. In general such package would be welcome unless it will require considerable maintenance overhead. Please let me know if need more info on this. Thanks,

**Comment by kliegeois** [comment]
@lyskov thanks for the message. I investigated this a bit. I am able to compile binder correctly (against llvm+clang installed by spack) but then, when I try to run the executable, I have the following error:

```
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted
``` 

Do you have thoughts on how I can resolve that?
clang seems to work.

**Comment by lyskov** [comment]
Hm... not sure what could be wrong here... - maybe double check that Binder source files linked only once? (ie that there is no duplicate in CMake file(s) )

**Comment by kliegeois** [comment]
The linking step looks like this:
```
/home/knliege/dev/spack/develop/lib/spack/env/gcc/g++ -Wl,--verbose -fno-rtti -O2 -g -DNDEBUG -rdynamic 
CMakeFiles/binder.dir/main.cpp.o CMakeFiles/binder.dir/binder.cpp.o CMakeFiles/binder.dir/context.cpp.o 
CMakeFiles/binder.dir/class.cpp.o CMakeFiles/binder.dir/config.cpp.o CMakeFiles/binder.dir/enum.cpp.o 
CMakeFiles/binder.dir/function.cpp.o CMakeFiles/binder.dir/options.cpp.o CMakeFiles/binder.dir/type.cpp.o 
CMakeFiles/binder.dir/util.cpp.o CMakeFiles/binder.dir/fmt/format.cc.o CMakeFiles/binder.dir/fmt/os.cc.o 
-o binder  -Wl,-rpath,/home/knliege/dev/spack/develop/opt/spack/linux-rhel7-skylake_avx512/gcc-7.2.0/llvm-11.1.0-j33d6jny7mumzubtlzte4zwdyad2cque/lib 
/home/knliege/dev/spack/develop/opt/spack/linux-rhel7-skylake_avx512/gcc-7.2.0/llvm-11.1.0-j33d6jny7mumzubtlzte4zwdyad2cque/lib/libLLVM.so 
/home/knliege/dev/spack/develop/opt/spack/linux-rhel7-skylake_avx512/gcc-7.2.0/llvm-11.1.0-j33d6jny7mumzubtlzte4zwdyad2cque/lib/libclang-cpp.so.11.1 
```
Do you see something wrong here?

**Comment by kliegeois** [comment]
@lyskov I tried with an older llvm. The spack install works with llvm 7 but not with llvm 11 nor 12. What are the supported llvm versions? I will try to create a PR to get the binder recipe into the spack repository but first I would like to improve the recipe to take into account supported llvm versions.

**Comment by lyskov** [comment]
@kliegeois i just double check our linking procedure and it looks like we have a few custom CMake directives that trigger different behavior depending on LLVM version. I think this is might be what trigger errors that you observe. Could you please take a look at our CMake file, particularly at lines: https://github.com/RosettaCommons/binder/blob/master/source/CMakeLists.txt#L78 https://github.com/RosettaCommons/binder/blob/master/source/CMakeLists.txt#L89 and see if it is possible to replicate this behavior in spack recipes? Thanks,

**Comment by lyskov** [comment]
> The spack install works with llvm 7 but not with llvm 11 nor 12.

-- thank you for that info, - this extra piece of info let me re-evaluate this error! @kliegeois i just double check our linking procedure and it looks like we have a few custom CMake directives that trigger different behavior depending on LLVM version. I think this is might be what trigger errors that you observe. Could you please take a look at our CMake file, particularly at lines: https://github.com/RosettaCommons/binder/blob/master/source/CMakeLists.txt#L78 https://github.com/RosettaCommons/binder/blob/master/source/CMakeLists.txt#L89 and see if it is possible to replicate this behavior in spack recipes? Thanks,

**Comment by kliegeois** [comment]
Thanks @lyskov for your comment, that makes a lot of sense.
I will try to use llvm 10 to see if it works. Then I may try to see how to update the [CMakeLists](https://github.com/RosettaCommons/binder/blob/master/source/CMakeLists.txt) to be compatible with llvm 11 and 12.

**Comment by kliegeois** [comment]
@lyskov I tried the following combinations with the spack build:

| LLVM major version  | Works ? |
| :---: | :---: |
| 7  | Yes  |
| 8  |  Yes |
| 9  | Yes  |
| 10  | No  |
| 11  | No  |
| 12  | No  |

**Comment by kliegeois** [comment]
Closing the issue as spack merged the Binder recipe.
