### ISSUE TITLE
Option -namespace A together with +class A::MyClass

### ISSUE THREAD

**Issue by kliegeois** [RosettaCommons/binder#247]
In #214 @lyskov, you suggested the usage of options such as:

```
-namespace A
+class A::MyClass
+function A::my_function
```
However, with the current implemented logic it is not feasible. The option `-namespace A` will dominate the logic to decide if the bindings need to be generated in this case.

As an example:

```


#ifndef TEST_STRUCT_H
#define TEST_STRUCT_H

#include <string>
#include <vector>
#include <memory>

namespace testers {

namespace subnamespace {
class Animal {
public:
	bool isAnimal() { return true;}
};
}

} // namespace testers

#endif

```
with options:

```
-namespace testers::subnamespace
+class testers::subnamespace::Animal
```
does not generate bindings for `testers::subnamespace::Animal`.

**Comment by lyskov** [comment]
As workaround: @kliegeois do want to disallow bindings for `testers::subnamespace` or just not explicitly request it? Ie i think this should work as intended if the following config options are used: `+class testers::subnamespace::Animal` (ie we simply do not initiate bindings for subnamespace). This however will not work if your project _do want to request_ bindings for global namespace (ie if you have `+namespace testers` in your config).

Re issues with exact flags: i just checked the code and it seems to be working as intended (though i do agree that it would be nice if explicit request for class/function bindings take priority). Let me see if it will be possible to refactor it so explicit requests for class/function bindings take priority.

**Comment by lyskov** [comment]
@kliegeois i just pushed 8fc011a which should fix this issue. Could you please see if it works for you? Thanks,

**Comment by kliegeois** [comment]
@lyskov your modification fixed the issue for the above mentioned example. Thanks!
