### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by andriish** [RosettaCommons/binder#249]
Hi @lyskov ,

would that make sense?

Andrii

**Comment by lyskov** [comment]
Absolutely, - there was a considerable amount of changes since last year release so i think we should make one. Let me see if anything else could be merged before that and i will make a new release soon.

**Comment by kliegeois** [comment]
@lyskov what is the expected timeline to do the release? Would it be feasible to wait for my PRs for #248 and #250 (I am working on these this week).

**Comment by lyskov** [comment]
I do not mind waiting a bit. I think #250 could be added fairly quickly but #248 might be a bit open ended and takes more time. Probably simplest solution would be to not worry about this and later do another release with minor version increment ( i do not see why not).

**Comment by kliegeois** [comment]
@lyskov Minor version increments would be great! It would be very helpful on my end.

**Comment by kliegeois** [comment]
Both #250 and #248 are closed; can we create a release in the near future?

**Comment by lyskov** [comment]
It is done: https://github.com/RosettaCommons/binder/releases/tag/v1.3.0
