### ISSUE TITLE
Compilation error on Windows Visual Studio 2015

### ISSUE THREAD

**Issue by hnokx** [RosettaCommons/binder#25]
Hello, I found some compilation errors on my environment.
1. and, or, not was not defined, perhaps some macros these are missing.

#define and &&
#define or ||
#define not !

https://stackoverflow.com/questions/555505/when-were-the-and-and-or-alternative-tokens-introduced-in-c/555524#555524
According to this, need to add another compilation option Za in case of VC++.

2. util.cpp needs to have #include <cctype> since it has std::isalpha.

3. context.cpp has invalid symbol(?) in the log like this.
outs() << "Generate bindings, pass №" << pass << "...\n";

**Comment by lyskov** [comment]
Thank you for letting me know @hnokx ! I just pushed f1ae4b7562ffab558f9c08cc0e479422d2dda11a which should address [2] and [3].

Re [1]: this is not a bug, Binder source is in C++11 so you need C++11 capable compiler. And yes using Za option for VC is probably the right approach.
