### ISSUE TITLE
Is there a way to exclude an enum?

### ISSUE THREAD

**Issue by andriish** [RosettaCommons/binder#254]
Hi @lyskov,

it seems there is no way to exclude an enum from the bindings. Moreover, the `std::_` enums are binded. Or am I missing some options that can prevent that?

Andrii

**Comment by andriish** [comment]
Oh, seems to be a duplicate of https://github.com/RosettaCommons/binder/issues/166.
Anyway.

**Comment by lyskov** [comment]
@andriish i just pushed the patch that adds `enum` config option which will allow to include/exclude enum's. Hope this helps!
