### ISSUE TITLE
Using binder on Mac?

### ISSUE THREAD

**Issue by juanborre** [RosettaCommons/binder#26]
Hello. We have some problems using this module.

We're trying to use binder to automatically generate python classes from our C++ code.

We've built binder using the script build.py and it has generated a binder binary.

When we execute that binary to generate the python wrappers, we get this error:
```
error: invalid argument '-std=c++11' not allowed with 'C/ObjC'
fatal error: 'vector' file not found
#include <vector>
```

We run it as it's specified here: http://cppbinder.readthedocs.io/en/latest/basics.html
With the std=c++11 option enabled but it seems the compiler does not accept that option and then it does not compile the code as if it were C++.

We're working on Mac and using clang. We tried passing the `--compiler clang++` argument to the build.py but it seems that compiler is only used to build binder and then binder uses another compiler to generate the wrapper that can't accept the std=c++ argument?

Does it happen because we are on a Mac architecture?
We've seen that you clone clang within the build folder. Is that the compiler you are using inside binder?
Do you know if binder is compatible with Mac? Maybe there is something that we are missing?

Thanks in advance for your answers.

**Comment by lyskov** [comment]
Hi @juanborre,

> Does it happen because we are on a Mac architecture?
- Binder should work on both Linux and Mac (as a self-test i routinely run it on ~3M LOC on both of these platforms)

> error: invalid argument '-std=c++11' not allowed with 'C/ObjC'
- This does not sounds right, could you please post the exact command line you was using? Particularly, have you tried to use `--compiler clang++` option as you mention above? (if so, see below)

>We're working on Mac and using clang. We tried passing the `--compiler clang++` argument to the 
 - if you need to specify compiler you need to us just basic name, like `--compiler gcc` or `--compiler clang`. I am guessing that attempting to pass clang++ might be the reason you getting these errors.

> build.py but it seems that compiler is only used to build binder 
  - this is correct.

> and then binder uses another
> compiler to generate the wrapper that can't accept the std=c++ argument?
  Not exactly, Binder itself act as sort of compiler in this situation. It parse code incoming C++ code but instead of compiling code it generate bindings source code. That source code you can lately compile with compiler of your choice to produce binaries that could be imported in Python.

Have you tried to look at: https://github.com/RosettaCommons/binder/blob/master/test/self-test.py ? - it will give a good idea of how to use Binder.

Let me know how it goes,

**Comment by juanborre** [comment]
Hi @lyskov ,

Thanks for the answer.

We first get this error when compiling binder (executing the tests)
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/17455105/29326152-701b200e-81b8-11e7-93fe-77a8f4f278de.png">

So we omitted the tests.

And then, we create a `binder_includes.h` file containing the following lines:
```
#include <Feed.h>
#include <RouteInfo.h>
```

Those files contain one class each and they include the `vector` file for C++.

We compile then using:
```
{path_to_binder}/bin/binder --root-module bgtfs_py_lib --prefix binder_files \
  --bind bgtfs_py_lib cpp/binder_includes.h -- -std=c++11 -I./submodules/transitLib/bgtfs/bgtfsLib/bgtfsLib \
  -DMY_PROJECT_DEFINE -DNDEBUG
```

as it's specified here:
http://cppbinder.readthedocs.io/en/latest/basics.html

We get then the following error:
<img width="718" alt="image" src="https://user-images.githubusercontent.com/17455105/29326375-4966bb0c-81b9-11e7-9ad9-5d79b2103ffe.png">

We noticed there is a ` -x c++` parameter to binder in the .py example that you sent. We added it to the command but still the result is the same.

Is there anything we are doing wrong?

Thanks in advance.

**Comment by lyskov** [comment]
@juanborre the first error is really confuse me. Basically it saying that compiler (clang++) could not find the Python.h header (while at the same time you _do_ specify `/usr/include/python2.7` as include path. Could you please verify that (a) you do have `Python.h` at that location and (b) What is your Mac OS version and `clang --version` string?

The second error: looks like you forgot to include path to system includes, please add this to `binder` command line (after the `--`) and see if thats make any difference.

`-isystem/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1`

Let me know how it goes,

**Comment by juanborre** [comment]
This is the clang version:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/17455105/29331397-4730c27c-81ca-11e7-87be-8bc37b9945bc.png">

The python.h file is not at that path but here:
```
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
```

If I add the include path it yields the following error (which is a different one)
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/17455105/29331582-ed2f78a8-81ca-11e7-8399-57dccc74c2be.png">

**Comment by lyskov** [comment]
Could you please try to rename your `cpp/binder_includes.h` file into `cpp/binder_includes.hpp` and try that again? The reason i am asking is that the very first error in your screenshot is `invalid argument -std=c++11 with C/ObjC` which only mean that LLVM treating your input include as C or ObjC file (while we want it be treated as C++). I guess later explained why some include could not be located.

**Comment by juanborre** [comment]
Sure, I did that and still getting the same error:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/17455105/29334442-66dad5f8-81d5-11e7-8558-8a558e9204d4.png">

And it seems that happens even if the file is not found (if I try to compile binder_includes.h but the file name is binder_includes.hpp I get this)
<img width="596" alt="image" src="https://user-images.githubusercontent.com/17455105/29334504-994b810e-81d5-11e7-8050-3f8a4e33f750.png">

**Comment by lyskov** [comment]
Hmmm... that does not compute, could you please post exact content of your build_binder.sh?

**Comment by lyskov** [comment]
Also, what is the version of your Mac OS and Xcode install?

**Comment by juanborre** [comment]
This is the `build_binder.sh`
```
#!/usr/bin/env bash

./binder/build/llvm-4.0/build_release_40.macos.Juans-DeLorean.local.release/bin/binder --root-module bgtfs_py_lib --prefix binder_files \
  --bind bgtfs_py_lib cpp/binder_includes.hpp -- -std=c++11 -I./submodules/transitLib/bgtfs/bgtfsLib/bgtfsLib \
  -DMY_PROJECT_DEFINE -DNDEBUG
```

**Comment by juanborre** [comment]
macOS Sierra 10.12.5
Xcode 8.3.3

**Comment by lyskov** [comment]
So, i do not see `-isystem/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1`? See a few post above, where i mentioned that this need to be added(after `--`) - without it Binder will not be able to find std lib includes...

**Comment by juanborre** [comment]
The error then is the one posted below too (where we wrote `If I add the include path it yields the following error (which is a different one)`)

**Comment by lyskov** [comment]
Ok, lets double check a few things:

- do you see file `vector` at path `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1`? (you should)

- what is the output of `which clang` and `which clang++`?

**Comment by juanborre** [comment]
Yes to the question. See screenshot for the whiches
<img width="614" alt="image" src="https://user-images.githubusercontent.com/17455105/29336946-9a377872-81dd-11e7-9067-f803c4fdffd7.png">

**Comment by lyskov** [comment]
ok, lets try to add ` -x c++` (again, after the `--`) just to in case...

**Comment by lyskov** [comment]
No, its not the same - this one is about `wchar.h` and previous one was about `<vector>`

**Comment by juanborre** [comment]
At this point, two thoughts:
- Renaming the binder_includes.h to binder_includes.hpp seems to have solved the C++ compilation. We don't get the C/ObjC error.
- Doing that without adding the include path to `c++/v1` yields the unable to find vector.
- Adding that include, the missing file is another one

**Comment by juanborre** [comment]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/17455105/29337450-4a591c0a-81df-11e7-8904-03d8150e4e83.png">

Yeah, it's posted below

**Comment by juanborre** [comment]
I'm currently trying this: https://stackoverflow.com/questions/26185978/macos-wchar-h-file-not-found

**Comment by lyskov** [comment]
So there is no `wchar.h` on my system (and i guess there is no such file on your Mac as well at -isystem/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1). So the question is why including <vector> lead to attempt to include wchar.h...

My guess is that some of the config files got messed up, i guess lets try obvious, like re-run `xcode-select --install` and see if that helps?

**Comment by lyskov** [comment]
> I'm currently trying this: https://stackoverflow.com/questions/26185978/macos-wchar-h-file-not-found
 - yep, we thinking along the same lines! Let me know if that helps.

**Comment by juanborre** [comment]
Well, it seems the wchar error is gone. I'm getting some errors now about our own .h files missing.
It looks like the problem is now on my code but it can take me some time to make the whole thing work. I will keep you posted with my findings.

Thanks, @lyskov, for your inestimable help!

**Comment by lyskov** [comment]
Awesome, thank you for letting me know @juanborre ! 

A few notes on includes: (1) (obvious) make sure that you have relevant `-I<path>` option in Binder that will point to your include locations. And (2) for technical reasons it is best to use C++ 'absolute' include location (i.e. `#include <myfile/something.h>`) instead of relevant one (i.e. '#include "something.h"')

I am going to close this for now, but please feel free to either re-open it or open new issue if problem is significantly different from this one.

**Comment by juanborre** [comment]
Hey @lyskov 
A quick heads-up on this matter.

We made it to compile binder and generate code for two of our files. This is our `bgtfs_py_lib.hpp.includes` file that we compile with binder:
```
#include <bgtfs/bgtfsLib/bgtfsLib/Feed.h>
#include <bgtfs/bgtfsLib/bgtfsLib/RouteInfo.h>
```

We compile then using cmake, including the .cpp generated and all the files included in the #.sources file.

It does not compile properly as we get this error:
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/17455105/29379004-093af83c-828f-11e7-9e91-1fd59dc25e38.png">
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/17455105/29379028-18d06ad4-828f-11e7-8d17-0a93a9ed4b79.png">

It seems that the generated code is trying to instantiate one of our classes without any parameter and there is no constructor with no parameters.

It's doing it in this line:
```

void bind_std_vector(std::function< pybind11::module &(std::string const &namespace_) > &M)
{
	{ // std::vector file:vector line:458
		pybind11::class_<std::vector<bgtfs::StopInfo>, std::shared_ptr<std::vector<bgtfs::StopInfo>>> cl(M("std"), "vector_bgtfs_StopInfo_t", "");
		pybind11::handle cl_type = cl;


...

                cl.def(pybind11::init<unsigned long>(), pybind11::arg("__n"));

...

}
```

It seems like a problem with the generated code? Is there something I might be missing?
The only constructor to that StopInfo class is:
> StopInfo(shared_ptr<Feed> feed, StopId stopId);

**Comment by lyskov** [comment]
This error arise because you trying to bind `std::vector` of `bgtfs::StopInfo` and some of the member functions of std::vector will require underlying class to have default constructor. You can try solving this by various means:

- define default constructor for your class

- use custom binder plugin for bindings std::vector (see http://cppbinder.readthedocs.io/en/latest/config.html#config-file-options). This could be setup to use either pybind11/include/pybind11/stl_bind.h functions (since it does not bind `resize` and constructor with size then it should not require default constructor) or Binder own version binder/source/stl_binders.hpp (this one however will also require default constructors so i mention it only to show you more example of how this could be done)

- disable binding for function that trigger requirement for default constructor, such as constructor with size, resize, ... etc.

- disable binding for whole `std::vector<bgtfs::StopInfo>` type

**Comment by juanborre** [comment]
Thanks @lyskov for your help!
