### ISSUE TITLE
Build script tries to use pybind11 commit that isn't on a branch (anymore?)

### ISSUE THREAD

**Issue by adamnovak** [RosettaCommons/binder#260]
The build script tries to check out `32c4d7e17f267e10e71138a78d559b1eef17c909`, but [that commit isn't on a branch in the pybind11 repo](https://github.com/pybind/pybind11/commit/32c4d7e17f267e10e71138a78d559b1eef17c909), so it fails for me.

Can the build script be updated to use a pybind11 commit that is on a branch and is also known to work?

**Comment by lyskov** [comment]
Done, i updated Pybind11 version to new commit (it is one of the releases) in cb9788e87286686762746532f624843e2f1972d0. Hope this helps!
