### ISSUE TITLE
Potential new release?

### ISSUE THREAD

**Issue by kliegeois** [RosettaCommons/binder#270]
For one of my project I am using the spack recipe of https://github.com/spack/spack/pull/38371 that relies on releases and that project actually needs #269 .

@lyskov Could we consider creating a new release in the near future?

**Comment by lyskov** [comment]
Sure thing, - it is about time we have next release. Let me see if there is anything else we might need to include in this release and I will take care of it.

**Comment by kliegeois** [comment]
Thanks @lyskov !

**Comment by lyskov** [comment]
OK, new release v1.4.0 is now available, - hope this helps @kliegeois
