### ISSUE TITLE
std::nullptr_t replacement to std::std::nullptr_t 

### ISSUE THREAD

**Issue by leibrandt-telos** [RosettaCommons/binder#279]
I tried a very simple example:
```
#pragma once
#include <ostream>

namespace test {
    class TestClass {
    public:
        explicit TestClass(int i);
        void print(std::ostream &stream) const;
        friend std::ostream & operator<<(std::ostream & s, TestClass const &);
    private:
        int value;
    };
}
```

When using `binder`  the following wrapper is generated: `std/basic_ios_tcc.cpp` ; the issues is that the following line gets generated:

```
cl.def("__lshift__", (std::ostream & (std::ostream::*)(std::std::nullptr_t)) &std::ostream::operator<<, "C++: std::ostream::operator<<(std::std::std::nullptr_t) --> std::ostream &", pybind11::return_value_policy::automatic, pybind11::arg(""));
```
which results into a compiler error: 
```
...
generated/std/basic_ios_tcc.cpp:84:58: error: no member named 'std' in namespace 'std'; did you mean simply 'std'?
                cl.def("__lshift__", (std::ostream & (std::ostream::*)(std::std::nullptr_t)) &std::ostream::operator<<, "C++: std::ostream::operator<<(std::std::std::nullptr_t) --> std::ostream &", pybind11::return_value_policy::automatic, pybind11::arg(""));
                                                                       ^~~~~~~~
                                                                       std
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/variant:59:11: note: 'std' declared here
namespace std _GLIBCXX_VISIBILITY(default)

```

I was able to locate the issue in: `binder/source/type.cpp`   where `make_pair("nullptr_t", "std::nullptr_t"),` replaces `nullptr_t` with `std::nullptr_t"` the issue however is that the left string (`nullptr_t`) is a substring of the right (`std::nullptr_t`) such that an input of `std::nullptr_t` will result into `std::std::nullptr_t`. A very simple solution is to add the reverse pair prior, wich results into:

```
make_pair("std::nullptr_t", "nullptr_t"),
make_pair("nullptr_t", "std::nullptr_t"),
```
as the strings get processed in order, this approach changes all `std::nullptr_t` to `nullptr_t` such that both `nullptr_t` and `std::nullptr_t` inputs get first converted to `nullptr_t` and in a second replace to `std::nullptr_t` which avoids `std::std::nullptr_t` ... I think that quick fix is a bit hacky. I would suggest to instead change the `replace` function such that a replacement only happens if the desired string is not already the input, however requires a tad more logic, to identify if the string is already the target string.

**Comment by lyskov** [comment]
Interesting, - thank you for isolating this @leibrandt-telos ! - Could you please post your environment info? Ie, which OS/GCC/Clang version was this run with? Thanks,

**Comment by leibrandt-telos** [comment]
Sure @lyskov , let me know if that is sufficient:
OS: Ubuntu 22.04
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang: Ubuntu clang version 15.0.7

**Comment by lyskov** [comment]
Hm... @leibrandt-telos i am still can't reproduce this. Could you please tell me which LLVM version do you use to build Binder?

**Comment by leibrandt-telos** [comment]
Yes @lyskov, it's the same version for llvm (15.0.7). I use the following cmake arguments to build binder:
```
"-DLLVM_DIR=/usr/lib/llvm-15/lib/cmake/llvm",
"-DClang_DIR=/usr/lib/cmake/clang-15",
```

I only install on ubuntu 22.04:
```
clang-15='1:15.0*' 
libclang-15-dev='1:15.0*' 
```
Does that help?

**Comment by lyskov** [comment]
Hm... i just tried to use LLVM 15.0.7 and still can't replicate this, - must be something specific how that install was made on you system... - sorry!

**Comment by lyskov** [comment]
Hm... i just tried to use LLVM 15.0.7 and still can't replicate this, - must be something specific how that install was made on you system...

- i will try building against LLVM installed with Ubuntu packages, - maybe that will bring a light to this situation.

**Comment by lyskov** [comment]
OK, i tried building against ubuntu LLVM-14 and LLVM-15 packages and still can't reproduce this 🤷🏻‍♂️. I will be happy to re-open this if you could provide Docker file that reproduce this. Thanks,
