### ISSUE TITLE
Release 1.4.1 or 1.4.2?

### ISSUE THREAD

**Issue by andriish** [RosettaCommons/binder#289]
Would that make sense to make release 1.4.1  or 1.4.2?

**Comment by lyskov** [comment]
@andriish i do not particularly mind that but do we have a good reason to do so? Ie was any recent bug fixes that will make release worth while in your view?

**Comment by andriish** [comment]
Hi @lyskov, no, there wer no bugfixes. However, there was quite a useful feature for the detection of the binder version. That is why the suggested change is the third digit.

**Comment by lyskov** [comment]
Ok, it is done: https://github.com/RosettaCommons/binder/releases/tag/v1.4.1
