### ISSUE TITLE
Config option to rename namespace (or join it contents with some other namespace, even global)

### ISSUE THREAD

**Issue by A1exStepanov** [RosettaCommons/binder#290]
It would be useful to make an option to rename namespace or join it contents with some other namespace.

Specifically, at the moment I need to move all bindings to the global namespace - maybe it is already possible to do this?

Regards, Alexey

**Comment by lyskov** [comment]
@A1exStepanov this is currently not possible. I also not sure if such option will fit well with overall Binder purpose and instead will be best to be delegated to supplemental `.py` package script that will serve as root import script for target package (in my experience any non-trivial package will require one). In Python script such manipulations could be done in very flexible manner directly in Python code. 

Note that while skeptical I am still open to discuss this idea so if you feel strongly that this task is best be done on Binder level then please argue why do you think it is a better idea comparing to doing so in Python script. Thanks,

**Comment by A1exStepanov** [comment]
Hi!
It was a proposal, not a special need.
Yes, as an option, I considered creating a py with something like:
```
from x import *
from x.ns import *
```
But maybe it's a little performance drawdown. So I just added about 10 lines of code to the **binder** for this functionality (without checking the same names etc). 

Thank you, I'm closing the issue

**Comment by lyskov** [comment]
@A1exStepanov re "performance drawdown": please note that this will only have impact on "import" performance (ie one time event) and should not have impact on "real code" performance.

> So I just added about 10 lines of code to the binder for this functionality (without checking the same names etc).
-- if you already implemented this and willing to put a PR then i will be happy to look at it (still no promise on it being merged though).

**Comment by boseong-Jeong** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***
          
          
            * Sent time : 
2024-03-29T03:03:36
          
          
            * Subject : 
Re: [RosettaCommons/binder] Config option to rename namespace (or join it contents with some other namespace, even global) (Issue #290)
          
          
            
              
                * Remote host said : 
              
              
                
대외비/기밀 메일은 외부 계정으로 발송이 제한되어 일부 메일 발송 실패(수신자가 전달 설정한 경우 포함)
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.

**Comment by lczech** [comment]
Hi there,

I have a follow-up question on this. I'd also be interested in a solution for that, in particular to move the root namespace (and everything in it, recursively) to the module level instead. I am trying to bind a large library (my bioinformatics code base [genesis](https://github.com/lczech/genesis) with close to 100k lines of code), which has all functionality under a common `genesis` namespace. Of course, I am naming the pybind module the same. Thus, my import now looks like this:

```.py
import genesis.genesis.something
```

which is a bit odd. 

What's the recommended way to just get `import genesis.something`?

Cheers and so long
Lucas

**Comment by lyskov** [comment]
@lczech I think I know exactly the issue that you facing: I had the similar issue for my main project, - Rosetta (for which Binder) was written and we solve it the following way:
-- The Python binding version of project was renamed to be `pyrosetta` which in turn contains `rosetta`, - shared library which provides all the binding interfaces to C++ code. 
-- So end package have two components: shared library and some Python code that provide various helper functions.
-- here is the link to package `__init__.py` in case you want to see how imports are handled: https://github.com/RosettaCommons/rosetta/blob/main/source/src/python/PyRosetta/src/pyrosetta/__init__.py#L15

I initially tried to keep bindings to be _just the shared library_ but it turned out to be not really feasible since for any non-trivial projects some Python level code support was a must. I do not know details of your project but unless it something really simple you most likely will need python level code if not to make it work but to make it easy to use.

Hope this helps,

**Comment by lczech** [comment]
Hi @lyskov,

thanks for the suggestion! Hm, I can see that having a dedicated Python initialization could be useful down the line, but at the moment I am where you once were: Trying to keep the bindings to just the shared library... you have more experience with this than me, so maybe I should listen to your advice on this :-) 

My project is also a bioinformatics library, [genesis](https://github.com/lczech/genesis), with about 100K lines of C++ code. So far, I did not need special Python code, but I am just in the beginning of working on bindings (my third attempt of tackling this...).

Anyway, looking at how the namespaces are resolved via the [ModuleGetter](https://github.com/RosettaCommons/binder/blob/46ec0e88137d368eeedafecfa123004f8ad028d1/source/context.cpp#L100), wouldn't it be possible to simply instruct that function to allow skipping the first namespace if it is identical with the module name? It should of course be an opt-in option to not break backwards compatibility.

So long
Lucas

**Comment by lyskov** [comment]
> Anyway, looking at how the namespaces are resolved via the [ModuleGetter](https://github.com/RosettaCommons/binder/blob/46ec0e88137d368eeedafecfa123004f8ad028d1/source/context.cpp#L100), wouldn't it be possible to simply instruct that function to allow skipping the first namespace if it is identical with the module name? It should of course be an opt-in option to not break backwards compatibility.

I am not sure I follow, could you please clarify why exactly do you want that?
