### ISSUE TITLE
Wrong code for MSVC

### ISSUE THREAD

**Issue by andriish** [RosettaCommons/binder#298]
In some cases binder will generate code that is not compatible with MSVC, e.g.

```
using _binder_ret_0 = class std::map<std::string, std::string >;
```

The following  code is will not compile in MSVC:

```
#include <stdexcept>
#include <string>
#include <map>
using _binder_ret_0 = class std::map<std::string, std::string >;
int main()
{
    _binder_ret_0 a;
    a["a"]="a";
    return 0;
}
```
but is OK for GCC.

To make the code compatible one should remove the "class" word.

```
using _binder_ret_0 = std::map<std::string, std::string >;
```

**Comment by lyskov** [comment]
resolved in https://github.com/RosettaCommons/binder/pull/299
