### ISSUE TITLE
Binder missing functions

### ISSUE THREAD

**Issue by peterbygrave** [RosettaCommons/binder#39]
I have built binder from github. I have tried to build pybind11 code using:
> binder --root-module test --bind "work" binder.cpp -- -std=c++11

for the C++:
> #ifndef THING_H
#define THING_H
#include \<vector>
namespace work{
struct Thing {
  double value;
};
std::vector\<Thing> get();
//inline std::vector\<Thing> get2() { return std::vector\<Thing>(); };
}
#endif

However, the function `get` does not get created unless I uncomment the last function `get2`. Am I doing something wrong?

**Comment by lyskov** [comment]
Yes, i encounter this issue in my other projects as well. What happening here is that LLVM/Clang does not fully instantiate templates if it "think" that they was not used. So Binder will look at the `std::vector<Thing>` and it will be reported as having no point of instantiation so Binder refuse to bind this type (without point of instantiation we can get access to member information to create bindings)

 This however happening only occasionally, one thing that seems to help is to explicitly instantiate template in question. So i guess try adding something like `template class std::vector<Thing>;` and see if it helps?

**Comment by peterbygrave** [comment]
I thought it might have been something like that, thanks for your help!

Just note that the template class definition need to come outside of any namespaces etc
