### ISSUE TITLE
Missing inherited constructor

### ISSUE THREAD

**Issue by peterbygrave** [RosettaCommons/binder#40]
When I have a class that inherits a constructor with the "using" phase, it is missing in the pybind11 code.

I think this is similar to issue #39 where here clang is optimising the constructor out. The only way I have been able to include it is by using the constructor in the header with `const b = B(1);` but the bigger issue there could be many constructors etc.

Any advice?

>#ifndef THING_H
#define THING_H
namespace work{
class A
{
    public:
        explicit A(int x) {}
};
class B: public A
{
     using A::A;
};
}
#endif

**Comment by lyskov** [comment]
Thank you for reporting this @peterbygrave! I will looks this up.

**Comment by lyskov** [comment]
Fixed in d39d19d1f6393a348ca9b608543e3543de4d96a8, let me know if you see further issues with `using` for constructors.

(Note that example code is missing `public:` in `B` class)

**Comment by lyskov** [comment]
Fixed in d39d19d, let me know if you see further issues with using for constructors.

(Note that example code is missing public: in B class)

**Comment by peterbygrave** [comment]
Yep that works on my end! Thanks for your efforts
