### ISSUE TITLE
test error：╮(╯▽╰)╭

### ISSUE THREAD

**Issue by yubingex007** [RosettaCommons/binder#43]
Encounter error while executing: diff /home/yubing/Documents/binder/test/T01.enum.ref /home/yubing/Documents/binder/test/build//T01_enum.cpp
37c37
< 		cl.def(pybind11::init<>());
---
> 		cl.def( pybind11::init( [](){ return new A(); } ) );

**Comment by yubingex007** [comment]
it can be compiled but encounter errors when it is tested

**Comment by lyskov** [comment]
@yubingex007 thank you for letting me know! Looks like tests files got outdated - i will look it up. For practice reasons however this could be ignored.

**Comment by lyskov** [comment]
fixed in 22e28fa46ae82aaed81a08fa0a5ea261a2f7d9c0
