### ISSUE TITLE
c++11 noexcept handling

### ISSUE THREAD

**Issue by thisiscam** [RosettaCommons/binder#5]
Currently I have a project that needs to utlize noexcept of c++11

The line of interest is here:
https://github.com/RosettaCommons/binder/blob/814d7c3a8f1eb809f78e05c01589f8289d09e3d2/binder/class.cpp#L482

After some digging I was still not able to find how I can fetch if the method decl has noexcept or not -- is it an attribute of the decl?

**Comment by lyskov** [comment]
Hmm, i do not see `noexcept` in an attribute list, so it might be implemented differently. Could you please post code snippet and briefly describe what problem does it trigger?

**Comment by thisiscam** [comment]
```
class RuntimeException : public std::exception {
private:
	std::string _message;
public:
	RuntimeException(const std::string &msg = "");
	virtual const char* what() const noexcept override;
};

```

Notice how there is a noexcept for method what(). The generated code currently doesn't add this attribute and the compiler give a static error saying 

` error: exception specification of
      overriding function is more lax than base version
        const char * what() const override { 
`

**Comment by thisiscam** [comment]
Ok I think I found the source regarding this

https://clang.llvm.org/doxygen/ExceptionSpecificationType_8h.html

Haven't looked at how to go from decl to this ExceptionSpecification though. 

Also, this means that other than noexcept, we shall probably handle exception throwing in general as well.

**Comment by lyskov** [comment]
Thank you @thisiscam , this was very helpful! I pushed the patch which i think should handle both `noexcept` and `throw()` cases, could you please test if this works for you?

**Comment by thisiscam** [comment]
Thanks for the prompt respoonse! works like a charm!

**Comment by lyskov** [comment]
Great, glad it helped!
