### ISSUE TITLE
Enum arithmetic

### ISSUE THREAD

**Issue by v-yatsenko** [RosettaCommons/binder#52]
Pybind11 supports exporting enums to be used in arithmetic operations.
cppbinder does not.
For example we have enum with fields containing a bit shifted values to be used as a flags:
```
enum Flags {
  flag1 = 1,
  flag2 = 1 << 1,
  flag3 = 1 << 2
}
```
Using pybind11 e may write:
```
pybind11::enum_<Flags>(m, "Flags", pybind11::arithmetic())
  .value("flag1", Flags::flag1)
  .value("flag2", Flags::flag2)
  .value("flag3", Flags::flag3)
  .export_values();
```
Also there are no possibility to provide custom binding for enums. Nor to exclude enum from generation (for example specifying -enum in config).

**Comment by lyskov** [comment]
@v-yatsenko just to make sure i understand you correctly: you want option for enums to be binded with use of `pybind11::arithmetic()`?

**Comment by v-yatsenko** [comment]
I had playing with this and have changes.
Please review.
[enum_arithmetic.patch.txt](https://github.com/RosettaCommons/binder/files/2429311/enum_arithmetic.patch.txt)

**Comment by lyskov** [comment]
Hmm... overhead for this should be minimal so lets go with automatically marking all non-class enums. I implemented this in 2e839c7, @v-yatsenko please see if that works for you. Thanks,

**Comment by v-yatsenko** [comment]
Thank you.
This looks good.
Only in your previous message probably you miss typed:

> go with automatically marking all non-class enums
You mean: all 'class enums'. Right?

**Comment by lyskov** [comment]
@v-yatsenko no, i specifically meant non-class enums there, why do you thin it should be otherwise?

**Comment by v-yatsenko** [comment]
> @v-yatsenko no, i specifically meant non-class enums there, why do you thin it should be otherwise?
From your change:
'''
	string maybe_arithmetic = E->isScopedUsingClassTag() ? ", pybind11::arithmetic()" : "";
'''
May be you interpret non-class enum term differently. I mean scopped using class tag enums.

**Comment by lyskov** [comment]
@v-yatsenko yes, that exactly what i mean: new C++11 strongly typed scoped enums will be bounded without use of `pybind11::arithmetic()` so they will behave exactly as in C++.

**Comment by lyskov** [comment]
@v-yatsenko yes, that exactly what i meant: new C++11 strongly typed scoped enums will be bounded without use of pybind11::arithmetic() so they will behave exactly as in C++.

(also code that you referring to is look like this string maybe_arithmetic = E->isScoped() ? "" : ", pybind11::arithmetic()";)
