### ISSUE TITLE
Compilation script doesn't work in my case

### ISSUE THREAD

**Issue by dgront** [RosettaCommons/binder#56]
I'm trying to compile binder. I'm following the script from documentation:
https://cppbinder.readthedocs.io/en/latest/install.html
but:

1) `llvm` required in the third stage is not `$HOME/prefix/llvm/`; I think the very first line of that script should be:
`cd $HOME/prefix/`
and `llvm` should be cloned here, right?

2) the symlink step doesn't work:
`ln -s $HOME/binder/binder $HOME/prefix/llvm/tools/clang/tools/extra/binder`
because there is no directory  `binder/binder` anywhere. Should I use `binder/source` instead?

3) Finally according to the script `cmake` should be executed in `$HOME/prefix/build`. This directory is empty (which is normal) but the directory one level up (`$HOME/prefix`) is also empty. So where should `cmake` be executed?

**Comment by lyskov** [comment]
@dgront have you tried to use build script https://github.com/RosettaCommons/binder/blob/master/build-and-run-tests.py to compile Binder - it should be the 'ultimate source of truth' of how it should be done...

**Comment by dgront** [comment]
Yes, the `build.py` script work fine, the issue may be closed. My only comment is that the _"latest"_ documentation may be updated at some point
