### ISSUE TITLE
final class workaround

### ISSUE THREAD

**Issue by thisiscam** [RosettaCommons/binder#6]
Is there a workaround  for final class? Currently the tool generates a subclass which cannot compile

**Comment by lyskov** [comment]
It should be possible to detect this and handle properly, - i am looking this up. In meanwhile: you can use config '-class <qualified-name>' directive to disable bindings for such classes.

**Comment by lyskov** [comment]
fixed in #d1140139c52d5a7b17ceddc6ed269f3f193d33c8
