### ISSUE TITLE
fatal errors from clang although the bindings are correct

### ISSUE THREAD

**Issue by yosoufe** [RosettaCommons/binder#64]
Hi, 
I am trying to make bindings for a single file in a large project. I get the clang file not found fatal error for the included header files which are only used in private sections of my classes and the their path are not included using `-I` in arguments. It seems that the generated bindings are correct. but the fatal error is annoying.
I do not know clang and ClangTool and ...
How can I suppress these fatal errors?
Is it possible to use something like [clang::Preprocessor::SetSuppressIncludeNotFoundError](https://clang.llvm.org/doxygen/classclang_1_1Preprocessor.html#ac7bafe67fc32e41460855b39d20ff6af)?

**Comment by lyskov** [comment]
@yosoufe i am not aware of the way to suppress fatal errors like that, but that function look promising. Have you tried using it locally? If so, could you please post code snippet or (probably better) open a PR with a path? Thanks,

**Comment by yosoufe** [comment]
@lyskov That is my problem. I do not know clang stuff and I do not have any idea were I should fit it inside. I googled like for few hours. No luck. I will do more to night.
[This is an example](https://github.com/loarabia/Clang-tutorial/blob/master/tutorial6.cpp) which is using clang::Preprocessor class but I do not know where it should be used in binder code.

**Comment by yosoufe** [comment]
In `binder.cpp` modifying the `BinderFrontendAction` class to following did what I wanted. It can be exposed as config to the binder.
```
class BinderFrontendAction : public ASTFrontendAction {
public:
    virtual std::unique_ptr<clang::ASTConsumer> CreateASTConsumer(CompilerInstance &ci, StringRef file) {
		clang::Preprocessor & preprocessor = ci.getPreprocessor();
		clang::DiagnosticsEngine& di = ci.getDiagnostics();
		di.setSuppressAllDiagnostics();
		preprocessor.SetSuppressIncludeNotFoundError(true);
        return std::unique_ptr<ASTConsumer>( new BinderASTConsumer(&ci) );
    }
};
```
