### ISSUE TITLE
Prefix path

### ISSUE THREAD

**Issue by lczech** [RosettaCommons/binder#7]
In order to get output files, I have to use a `binder --prefix path/to/out/` path that ends with a slash. This is [not documented](http://cppbinder.readthedocs.io/en/latest/basics.html), and could be fixed easily ;-)

**Comment by lyskov** [comment]
Oh, this is actually done on purpose: the idea is that in cases we can use prefix that specify file-name-prefix instead of being limited to specifying only directory prefix. But good point about documentation! @xlong2 could you please looks this up?

**Comment by xlong2** [comment]
Yes I'll do documentation regarding this ASAP.

**Comment by lczech** [comment]
That is a nice idea, but not working on my system. When I call `binder --prefix path/to/out` with no trailing slash, I get the main files `outlibname.cpp`, `outlibname.modules` etc in `path/to`. I also get a directory there named `out`, which contains all the correct subdirectories for my lib. But none of those directories contains any files. So, apart from the top-level main files in `path/to/`, there are no files in `path/to/out/`.

Running on Ubuntu 14.04, with the most recent binder version from three days ago, installed using the `build.py` script.

**Comment by everyday847** [comment]
Ah, so it sounds like an interaction between using a filename prefix with binding a library with subdirectories? In the simplest cases it might still work fine.
