### ISSUE TITLE
Using typedefed name rather than underlying name

### ISSUE THREAD

**Issue by yosoufe** [RosettaCommons/binder#75]
Hi. Is there anyway thay I would be able to use the name that has been defined via typedef rather than the underlying name?

for example
```C++
namespace myNamespace
{

template <class T>
class myType
{
// ....
}

// instantiate the template
template class myType<int>;

typedef myType<int> myTypeInt;

myTypeInt var;

void someFunction(myTypeInt& in) { /* do something */ }

} // end of namespace
```
For me binder generates a class name for `myTypeInt` something like `myNamespace_myType_int_t` while It would make sense to generate as the typedefed one as `myTypeInt` here.

I have surfed  a lot the doxygen documents of clang toolings, not found a clean solution there. The only thing that comes to my mind is that [here in binder.cpp](https://github.com/RosettaCommons/binder/blob/master/source/binder.cpp#L178) which is commented out, we populate  a `std::map<std::string , std::string>` which maps for example here from `myType<int>` to `myTypeInt` and then in [class.cpp](https://github.com/RosettaCommons/binder/blob/master/source/class.cpp#L69) check if the name exists in the map , if yes we could use the typedefed name. what do you think?

**Comment by lyskov** [comment]
Hi @yosoufe ! 
Right now there is no mechanism to achieve this. I have plan to implement something similar: idea is to add `alias` config directive which will allow user to specify handle aliases for given type. Issue with typedef is that there could be multiple typedef's for single declaration so binding them all automatically sounds wrong to me.

Best,

**Comment by yosoufe** [comment]
Ok. Then I close this

**Comment by A1exStepanov** [comment]
Hi, @lyskov !
Is there any progress in "alias" functionality?

All the best, Alexey

**Comment by lyskov** [comment]
@A1exStepanov unfortunately i still have not got time to implement this. As a workaround: easy way to work around this would be to add custom `.py` file for you project that create such aliases on the fly. Here is the example how we do this in our project: https://github.com/RosettaCommons/rosetta/blob/main/source/src/python/PyRosetta/src/pyrosetta/__init__.py#L18 (the `rosetta` here is namespace generated by Binder)

**Comment by A1exStepanov** [comment]
Thanks for the advice!
