### ISSUE TITLE
method default arguments

### ISSUE THREAD

**Issue by Martinii89** [RosettaCommons/binder#78]
Is it possible to make binder generate code that includes default arguments for methods?
https://pybind11.readthedocs.io/en/stable/basics.html#default-args

```
// regular notation
m.def("add1", &add, py::arg("i") = 1, py::arg("j") = 2);
// shorthand
m.def("add2", &add, "i"_a=1, "j"_a=2);
```

**Comment by Martinii89** [comment]
I did this change. it seems to do the trick. I don't really llvm and clang at all, so this is probably not the best way to do it..
```cpp
	for(uint i=0; i<F->getNumParams()  and  i < args_to_bind; ++i) {
		r += ", \"{}\"_a"_format( string( F->getParamDecl(i)->getName() ) );
		if (F->getParamDecl(i)->hasDefaultArg())
		{
			LangOptions Langopts;
			Langopts.CPlusPlus = true;
			PrintingPolicy policy(Langopts);
			std::string buf;
			raw_string_ostream out(buf);
			auto arg = F->getParamDecl(i)->getDefaultArg();
			arg->printPretty(out, nullptr, policy, 0);
			out.flush();
			//outs() << buf << "\n";
			r += " = {0}"_format(buf);
		}

		if(request_bindings_f) request_bindings( F->getParamDecl(i)->getOriginalType(), context);
	}
```

**Comment by lyskov** [comment]
To handle default arguments Binder generate set of lambda functions instead of relaying on Pybind11 default-arg functionality. This is because these two methods have different evaluation strategy: default arg in Pybind11 will be evaluated _*once*_ (Python evaluation strategy ) while default arg in lambda will be evaluated each time function is called (C++ evaluation strategy). Since we binding C++ code it will be less surprising for user to have the later.

**Comment by Martinii89** [comment]
What do you mean default arg in pybind will only be evaluated once? And which issues can come from this? I'm currently not seeing any issues with calling a c++ function from python with different varying amounts of arguments.

**Comment by lyskov** [comment]
Consider this: in C++ we have function `void foo(int a=get_a_default())` 

- if default argument for this function bound with lambda it would behave in Python exactly as in C++ - the `a` default argument will be calculated each time when we call `foo()` by calling `get_a_default()` function. 

- However if foo default arg is bound thorough Pybind11 default arg machinery then `a` default value will be calculated _only once_ during binding phase which will be surprising behavior for user.

**Comment by andriish** [comment]
Hi @lyskov ,

This issue is resolved, isn't it?

Best regards

Andrii

**Comment by lyskov** [comment]
@andriish yes, - closing now
