### ISSUE TITLE
add_on_binder equivalent for module-level functions

### ISSUE THREAD

**Issue by simleo** [RosettaCommons/binder#79]
I use `add_on_binder` to add method bindings to existing classes. Is there any way to do something similar for module-level functions? I.e., is it possible to have binder add custom `M("foo").def(...)` sections to the set of bindings for namespace `"foo"`?

**Comment by lyskov** [comment]
Right now there is no such functionality (but it looks like a good feature to have so i am adding this to my list) but you can emulate this with following workaround: If you know unique name of the type in namespace that you want to hand-bind then you can add two directives into binder.config files: [a] use `+include` to add file which will have your module-binding-function and [b] use `+binder` or `+add_on_binder` to trigger function call for your module-binding-function. Here is concrete example from Rosetta code base to illustrate this:

Suppose we want to provide hand-written-binding-function for namespace `protocols::indexed_structure_store` and we have `protocols::indexed_structure_store::StructureStore` class in that namespace. Then we can add the following line to our Binder-config files:
```
+include_for_class protocols::indexed_structure_store::StructureStore <protocols/indexed_structure_store/StructureStore.py.hh>
+binder protocols::indexed_structure_store::StructureStore protocols::indexed_structure_store::bind_StructureStore<pybind11::module>
```

Now, inside `protocols/indexed_structure_store/StructureStore.py.hh` file we can write our module binding function like this:
```C++
template<typename Module> void bind_StructureStore(Module & m)
{
...
}
```

**Comment by simleo** [comment]
Thanks, the workaround seems to work. I had to add a dummy empty class and use that one for `include_for_class`, since if I use an existing one then the bindings for that class are not generated anymore.

**Comment by lyskov** [comment]
Glad it worked! @simleo i also just pushed update which adds `include_for_namespace`, `binder_for_namespace` and `add_on_binder_for_namespace` config directives which should allow you to directly specify module level bind function. Please see related documentation at https://cppbinder.readthedocs.io/en/latest/config.html and example usage here: https://github.com/RosettaCommons/binder/blob/master/test/T50.namespace_binder.config
