### ISSUE TITLE
Using binder for templated class

### ISSUE THREAD

**Issue by luizcmarques** [RosettaCommons/binder#80]
I modified the example including a template argument to the struct
binder does not go through "pass 2"  and does not generate the "test_struct" directory
binder does not generate an explicit error message...

Is there a project with templated classes I could use as example to learn from?

I modified the example code as :
namespace testers {

template \<class FF\>
struct test_my_struct {
	int an_int;
	std::string a_string;
	std::vector<int> a_vector;
	float a_float;

	test_my_struct() {
		an_int = 27;
		a_string = "TEST_STRING";
		a_vector = std::vector<int>{1,2,3,4,5};
		a_float = 88.88;
	}
	void	increment_int() {
		++an_int;
	}
	void	add_float() {
		a_float += 22.22;
	}
	void	append_vec() {
		a_vector.push_back(a_vector.back()+1);
	}
};
template struct test_my_struct\<double\>;
}

**Comment by danpf** [comment]
templated structs/classes are a little weird, the only way i'm aware of that will fully instantiate them is to use them as an argument in a function:


```
namespace testers {

template <typename T>
struct test_my_struct {
...
	T templ_;

....
	test_my_struct(T const & t_in) {
...
		templ_ = t_in;
	}
...
};

// Instantiated as a functions argument 
void f_001(test_my_struct<int>) {}
void f_002(test_my_struct<std::string>) {}
}
```

this yields two bound objects:
```
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'testers']
['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'f_001', 'f_002', 'test_my_struct_int_t', 'test_my_struct_std_string_t']
```

**Comment by lyskov** [comment]
As @danpf already mentioned: in order for Binder to be able to create bindings for template types they have to be fully instantiated. The simplest way to do so is to fully specify template parameters and inherit from such type. 

For instance for your example this could be done as `struct MyStructDouble : public test_my_struct<double> {};`. 

Hope this helps,

**Comment by luizcmarques** [comment]
Lyskov and Danpf, thank you for help. 

Our C++ library is quite large and uses lots of templated classes, so the approach to have bindings for those classes will be very important to determine total effort. 
I'll try your suggestions on a smaller subset of library to have a working method. Later on, I'll target
whole library with same method.

Thanks again!
