### ISSUE TITLE
Adding pybind11 annotations to class_ definitions

### ISSUE THREAD

**Issue by simleo** [RosettaCommons/binder#81]
Is it possible to have binder add extra pybind11 annotations (e.g., `buffer_protocol`) to generated `class_` definitions? For instance, I'm getting:

```
pybind11::class_<Foo, std::shared_ptr<Foo>> cl(M(""), "Foo", "");
```

But I need:

```
pybind11::class_<Foo, std::shared_ptr<Foo>> cl(M(""), "Foo", pybind11::buffer_protocol());
```

Thanks!

**Comment by lyskov** [comment]
Could you please elaborate on this? I was not able to find any reference to `buffer_protocol` in Py ind11 docs: https://pybind11-rtdtest.readthedocs.io/en/stable/search.html?q=buffer_protocol&check_keywords=yes&area=default 

I only see related info in https://pybind11-rtdtest.readthedocs.io/en/stable/advanced.html#buffer-protocol but it does not look like to what you proposing.

**Comment by simleo** [comment]
There's an example in https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html where a C++ data structure is exposed as a buffer object. This uses the `def_buffer` method, but it only works if the `pybind11::class_` constructor specifies the `pybind11::buffer_protocol()` annotation. While the `def_buffer` part can be added via `add_on_binder`, there seems to be no way to control the definition of the `pybind11::class_` constructor in binder.

**Comment by lyskov** [comment]
Well, it is clear to me now that i will unlikely have to implement this in near future. So i will be closing this for now. However PR that will introduce support for this will be welcome.
