### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by marcelotrevisani** [RosettaCommons/binder#83]
is it possible to create releases for this project?

In that way, I would be able to download the project from tarballs instead of cloning it.

**Comment by lyskov** [comment]
Sure @marcelotrevisani, i added initial release, please download it at https://github.com/RosettaCommons/binder/releases/tag/v1.0.0

**Comment by marcelotrevisani** [comment]
> Sure @marcelotrevisani, i added initial release, please download it at https://github.com/RosettaCommons/binder/releases/tag/v1.0.0

Thank you! I am going to create a conda package on ``conda-forge`` for this project! :)

**Comment by lyskov** [comment]
That’s awesome @marcelotrevisani ! Could you please ping me when it’s done so I can refer ppl to it when they ask about Conda package? Thanks,
