### ISSUE TITLE
Unused `cl_type` definitions

### ISSUE THREAD

**Issue by simleo** [RosettaCommons/binder#84]
Binder adds the following line for each class it binds:

`pybind11::handle cl_type = cl`

However, `cl_type` is never used afterwards. This leads to a lot of unused-but-set-variable warnings while compiling the generated code.

**Comment by lyskov** [comment]
Thank you for letting me know @simleo ! Indeed, looks like this variable is no longer needed, - i will looks this up.

**Comment by lyskov** [comment]
Fixed in 135f6e3b2de42bc3601b237d59e95499eee4acc4
