### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by lczech** [RosettaCommons/binder#9]
The [Build Instructions](http://cppbinder.readthedocs.io/en/latest/install.html) should mention that `ninja` is needed for compiling binder.

The provided shell sequence does not work. Checking out clang releases requires `origin/...` before the branch name, and the cmake command does not find its list file in the provided path.

Also, I first tried to follow the shell sequence, before I saw that there is a `binder/install.py`, which make it easier. This could be highlighted a bit better ;-)

**Comment by lyskov** [comment]
Great, thank you for letting me know! This should be fixed now in ab822f268ddbe80af61ce1d154b3edc94cf3251c.
