### ISSUE TITLE
Error on building installation

### ISSUE THREAD

**Issue by Worsman** [RosettaCommons/binder#90]
-- Clang version: 3.8.1
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG - Failed
CMake Error at tools/clang/tools/extra/binder/CMakeLists.txt:37 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "binder".  All uses of target_link_libraries with a target must
  be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * cmake/modules/LLVM-Config.cmake:74 (target_link_libraries)

-- Configuring incomplete, errors occurred!

**Comment by lyskov** [comment]
What version do you use? I do not see this issues when building latest master.

**Comment by Worsman** [comment]
I am referring to the steps listed here [steps with Error](https://cppbinder.readthedocs.io/en/latest/install.html)
Will now try the steps in listed at [ steps to try next](https://github.com/RosettaCommons/binder/blob/master/documentation/install.rst)

**Comment by Worsman** [comment]
steps in [correct steps](https://github.com/RosettaCommons/binder/blob/master/documentation/install.rst) where succesfull.
