### ISSUE TITLE
 **recursively** include all #include <header.h>

### ISSUE THREAD

**Issue by Worsman** [RosettaCommons/binder#92]
Would the recommendation be to **recursively** include all #include <header.h> in the all-including header.hpp file?? For larger projects, this could lead to very large list of files despite only wanting to expose a subset of classes.

example:

CClassA.h >> have 2 includes  
CClassB.h & CClassC.h
but each of B & C also have 2 x includes 

this means all-including header.hpp >> 
#include <CClassA.h>
#include <CClassB.h>
#include <CClassC.h>

#include <CClassD.h>
#include <IncludePathY\CClassE.h>

#include <IncludePathX\CClassF.h>
#include <CClassG.h>

what makes it more complicated it this includes relying on project level include paths to resolve

OR am I misunderstanding the aim of the listing in the all-including header.hpp??

_Originally posted by @Worsman in https://github.com/RosettaCommons/binder/issues/10#issuecomment-579216207_

**Comment by lyskov** [comment]
The purpose of all-includes.hpp file is to provide all declarations for classes/functions thats need to be exposed into Python. So say if you only need to expose single class then putting only header(s) that define this class would be sufficient.

**Comment by Worsman** [comment]
I started with only 1 include line in all-includes.hpp with the idea to only get bindings fort for this class. The errors that returned where mostly "use of undeclared identifier" and I assumed this would be due to not including the header files for the error types. I then attempted to add the header files but that results in a never-ending loop of possible adding all possible files referenced in project

It seems I am unable to define/config binder to limit it to only 1 class/header file

**Comment by ahellerjones** [comment]
As far as I understand, it's still impossible to recursively include headers? It doesn't seem like there's any way to add some kind of include path to look in in the initial `binder` command which would be really nice. I'm having the issue of using legacy code which uses external headers that are simply defined in the gcc include path, however when Binder sees them it has no idea what to do with them. Pretty much the same issue as OP, ClassA depends on file.h, file.h is located very far far away from where ClassA is.

**Comment by lyskov** [comment]
@ahellerjones are you talking about a way to generate bindings for all headers located in some dir? If so then this is separate issue and it is outside the scope of Binder and should be handled by the higher level scripts. For my project i just have a single Python scripts that walk through all files inside particular dir and collect all .hh files to later write them into `all-include.hh` file.

**Comment by ahellerjones** [comment]
@lyskov Thanks for the reply; sort of, my issue is that I have a lot of cpp files who's #include's use angle brackets, `#include <far/away/directory>` which were resolved using some thing like `gcc -I far/`. However, when I run `binder`, I can't seem to find any to make an include path for binder to look down. Is this a functionality that can be done in the .cfg? 

Right now my solution has been to have a script collect all of my needed includes and make hard links to them in a 'linked_includes' directory, and then soft links in 'linked_includes' to the paths specified by #include <path/to/more/headers>, but this tends to break when a header uses a #include <...> as it requires #include "" to look down these soft paths.

**Comment by lyskov** [comment]
No worries, @ahellerjones! - glad to hear it worked out!
